// Reads forge build artifacts and contract deployments, emits web/lib/contracts.ts.
// Run: pnpm gen:abis  (from web/ directory)
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const root = join(__dir, '../..');
const outDir = join(root, 'contracts/out');
const sepoliaFile = join(root, 'contracts/deployments/sepolia.json');
const mainnetFile = join(root, 'contracts/deployments/mainnet.json');
const libDir = join(__dir, '../lib');
const outputFile = join(libDir, 'contracts.ts');

mkdirSync(libDir, { recursive: true });

const sepolia = JSON.parse(readFileSync(sepoliaFile, 'utf8'));
const mainnet = JSON.parse(readFileSync(mainnetFile, 'utf8'));

const names = [
  'AgentRegistry',
  'SentinelGuard',
  'ReputationOracle',
  'SafetyRules',
  'EmergencyVault',
  'AgentIdentityRegistry',
];

// The identity registry was named MockIdentityRegistry on the Sepolia dry-run
// suite (deployed pre-rename) and AgentIdentityRegistry on mainnet. Same ABI;
// resolve whichever key the deployment file uses.
const identityAddress = (deploy) =>
  (deploy.contracts.AgentIdentityRegistry ?? deploy.contracts.MockIdentityRegistry).address;

let out = `// AUTO-GENERATED by web/scripts/gen-abis.mjs — do not edit by hand.
// Run: pnpm gen:abis
import type { Address } from 'viem';

`;

// Contracts that must be deployed from the frontend (need bytecode too)
const withBytecode = new Set(['SafetyRules']);

for (const name of names) {
  const artifact = JSON.parse(
    readFileSync(join(outDir, `${name}.sol/${name}.json`), 'utf8'),
  );
  out += `export const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
  if (withBytecode.has(name)) {
    out += `export const ${name}Bytecode = '${artifact.bytecode.object}' as const;\n\n`;
  }
}

out += `// ── Deployed addresses ──────────────────────────────────────────────────────
export const DEPLOYMENTS = {
  sepolia: {
    chainId: ${sepolia.chainId} as const,
    AgentRegistry: '${sepolia.contracts.AgentRegistry.address}' as Address,
    SentinelGuard: '${sepolia.contracts.SentinelGuard.address}' as Address,
    ReputationOracle: '${sepolia.contracts.ReputationOracle.address}' as Address,
    EmergencyVault: '${sepolia.contracts.EmergencyVault.address}' as Address,
    AgentIdentityRegistry: '${identityAddress(sepolia)}' as Address,
    explorerBase: 'https://explorer.sepolia.mantle.xyz',
  },
  mainnet: {
    chainId: ${mainnet.chainId} as const,
    AgentRegistry: '${mainnet.contracts.AgentRegistry.address}' as Address,
    SentinelGuard: '${mainnet.contracts.SentinelGuard.address}' as Address,
    ReputationOracle: '${mainnet.contracts.ReputationOracle.address}' as Address,
    EmergencyVault: '${mainnet.contracts.EmergencyVault.address}' as Address,
    AgentIdentityRegistry: '${identityAddress(mainnet)}' as Address,
    explorerBase: 'https://mantlescan.xyz',
  },
} as const;

// address(0) is the NATIVE key for MNT inside SentinelGuard.balanceOf
export const NATIVE_TOKEN = '0x0000000000000000000000000000000000000000' as Address;

// Known ERC-20 tokens on Mantle Mainnet (not yet deployed on Sepolia testnet)
export const KNOWN_TOKENS = {
  mETH:  '0xcDA86A272531e8640cD7F1a92c01839911B90bb0' as Address,
  USDY:  '0x5bE26527e817998A7206475496fDE1E68957c5A6' as Address,
  USDe:  '0x5d3a1Ff2b6BAb83b63cd9AD0787074081a52ef34' as Address,
} as const;
`;

writeFileSync(outputFile, out);
console.log('✓  contracts.ts written to web/lib/contracts.ts');
