'use client';

import { useEffect, useState } from 'react';

interface Props {
  agent: string;
  net: string;
  paused: boolean;
}

interface ExplainResponse {
  status?: string;
  explanation?: string;
  error?: string;
}

export function AiIncidentReport({ agent, net, paused }: Props) {
  const [text, setText] = useState<string | null>(null);
  const [failed, setFailed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch(`/api/agent/${agent}/explain?net=${net}`);
        const data = (await res.json()) as ExplainResponse;
        if (cancelled) return;
        if (!res.ok || !data.explanation) {
          setFailed(true);
          return;
        }
        setText(data.explanation);
      } catch {
        if (!cancelled) setFailed(true);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [agent, net]);

  // Stay silent on failure (e.g. AI not configured) — never block the page.
  if (failed) return null;

  const accent = paused ? 'text-sentinel-danger' : 'text-sentinel-cyan';
  const label = paused ? '✦ AI Incident Report' : '✦ AI Status Summary';

  return (
    <div
      className={`surface p-5 space-y-2 animate-fade-up ${
        paused ? 'border-sentinel-danger/40' : 'border-sentinel-cyan/30'
      }`}
    >
      <div className="flex items-center justify-between">
        <p className={`eyebrow ${accent}`}>{label}</p>
        <span className="font-mono text-[10px] text-sentinel-gray-1">
          generated by Claude via DGrid
        </span>
      </div>
      {text ? (
        <p className="font-mono text-xs text-sentinel-white leading-relaxed">{text}</p>
      ) : (
        <div className="space-y-1.5 animate-pulse" aria-label="generating">
          <div className="h-3 bg-sentinel-gray-2 rounded w-full" />
          <div className="h-3 bg-sentinel-gray-2 rounded w-4/5" />
        </div>
      )}
    </div>
  );
}
